#!/bin/bash

echo "Setting up Network Mirror"
cat >> "${HOME}/.terraformrc" << EOF
disable_checkpoint = true
provider_installation {
    direct {
        exclude = ["registry.terraform.io/*/*"]
    }
    network_mirror {
        url = "https://shriram-network-mirror.s3.ap-south-1.amazonaws.com"
        include = ["registry.terraform.io/*/*"]
    }
}

EOF
